# fly.toml app configuration file generated for ranking-front-web on 2023-08-20T12:47:20+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "ranking-front-web"
primary_region = "nrt"

[build]

[http_service]
internal_port = 3000
force_https = true
auto_stop_machines = false
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

[env]
NEXT_PUBLIC_API_URL = "desk-items-api.internal"
